#!/usr/bin/env python3
"""Fetch structured tweet data from X's oEmbed endpoint for every URL in
_data/featured_tweets.yml and write _data/tweets_rendered.yml.

Templates render their own clean card layout from these fields rather
than using the oEmbed "citation" HTML directly.

Usage:  python3 scripts/fetch_tweets.py
Rerun whenever _data/featured_tweets.yml changes.
"""
from __future__ import annotations

import json
import re
import sys
import urllib.parse
import urllib.request
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "_data" / "featured_tweets.yml"
DST = ROOT / "_data" / "tweets_rendered.yml"

UA = "Mozilla/5.0 (compatible; ConvAIFetcher/1.0)"


def read_urls(path: Path) -> list[str]:
    urls: list[str] = []
    with path.open() as f:
        for line in f:
            m = re.match(r"\s*-\s*url:\s*(\S+)", line)
            if m and m.group(1).startswith("http"):
                urls.append(m.group(1))
    return urls


def fetch_oembed(url: str) -> dict | None:
    embed_url = url.replace("https://x.com", "https://twitter.com")
    query = urllib.parse.urlencode(
        {"url": embed_url, "omit_script": "true", "dnt": "true"}
    )
    api = f"https://publish.twitter.com/oembed?{query}"
    req = urllib.request.Request(api, headers={"User-Agent": UA})
    try:
        with urllib.request.urlopen(req, timeout=20) as resp:
            if resp.status != 200:
                return None
            return json.loads(resp.read().decode("utf-8"))
    except Exception as e:
        print(f"  ! oembed error: {e}", file=sys.stderr)
        return None


def fetch_syndication(tweet_id: str) -> dict | None:
    # cdn.syndication.twimg.com serves structured tweet data (text, avatar,
    # media attachments). Accepts a simple "token=x" noop in practice.
    query = urllib.parse.urlencode({"id": tweet_id, "token": "x"})
    api = f"https://cdn.syndication.twimg.com/tweet-result?{query}"
    req = urllib.request.Request(api, headers={"User-Agent": UA})
    try:
        with urllib.request.urlopen(req, timeout=20) as resp:
            if resp.status != 200:
                return None
            return json.loads(resp.read().decode("utf-8"))
    except Exception as e:
        print(f"  ! syndication error: {e}", file=sys.stderr)
        return None


def tweet_id_from_url(url: str) -> str:
    m = re.search(r"/status/(\d+)", url)
    return m.group(1) if m else ""


def upscale_avatar(url: str) -> str:
    # Twitter default serves "_normal.jpg" (48x48). Swap for 400x400.
    if not url:
        return ""
    return re.sub(r"_normal(\.[a-zA-Z]+)$", r"_400x400\1", url)


def extract_body(oembed_html: str) -> str:
    m = re.search(r"<p\b[^>]*>(.*?)</p>", oembed_html, re.DOTALL)
    if not m:
        return ""
    body = m.group(1).strip()
    # Drop pic.twitter.com/pic.x.com attachment links (pure noise when
    # rendering text-only cards — there's no image we'd resolve to).
    # The link text starts with "pic.twitter.com" or "pic.x.com"; the href
    # is a t.co shortlink so we can't match by href alone.
    body = re.sub(
        r"\s*<a\b[^>]*>\s*pic\.(?:twitter|x)\.com[^<]*</a>\s*",
        "",
        body,
    )
    # Drop trailing ellipsis or whitespace left dangling after the strip
    body = re.sub(r"[\s…]+$", "", body).strip()
    body = re.sub(r"(?:\s*<br\s*/?>\s*)+$", "", body).strip()
    return body


def extract_date(oembed_html: str) -> str:
    m = re.search(r"<a\b[^>]*>([^<]*\d{4})</a>\s*</blockquote>", oembed_html)
    if not m:
        return ""
    raw = m.group(1)
    try:
        return datetime.strptime(raw, "%B %d, %Y").strftime("%b %-d, %Y")
    except ValueError:
        return raw


def handle_from_url(author_url: str) -> str:
    m = re.search(r"/([^/]+)/?$", author_url or "")
    return m.group(1) if m else ""


def yaml_str(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)


def main() -> int:
    if not SRC.exists():
        print(f"missing {SRC}", file=sys.stderr)
        return 1

    urls = read_urls(SRC)
    out: list[str] = [
        "# Generated by scripts/fetch_tweets.py — do not edit by hand.",
        "# Rerun the script after editing _data/featured_tweets.yml.",
        "",
    ]

    fetched = 0
    skipped = 0
    for idx, url in enumerate(urls, 1):
        print(f"[{idx}/{len(urls)}] {url}")
        data = fetch_oembed(url)
        if not data:
            print("  ! skipped (oembed failed)")
            skipped += 1
            continue

        author = data.get("author_name", "")
        author_url = data.get("author_url", "")
        handle = handle_from_url(author_url)
        html = data.get("html", "")
        body = extract_body(html)
        date = extract_date(html)
        is_repost = "/convai_uiuc/status/" not in url.lower()

        # Enrich with syndication data: avatar + media images
        avatar = ""
        images: list[str] = []
        tid = tweet_id_from_url(url)
        if tid:
            synd = fetch_syndication(tid)
            if synd:
                user = synd.get("user") or {}
                avatar = upscale_avatar(user.get("profile_image_url_https", ""))
                for m in synd.get("mediaDetails") or []:
                    if m.get("type") in (None, "photo") and m.get("media_url_https"):
                        images.append(m["media_url_https"])

        out.append(f"- url: {url}")
        out.append(f"  author: {yaml_str(author)}")
        out.append(f"  handle: {handle}")
        out.append(f"  author_url: {author_url}")
        out.append(f"  avatar: {avatar}")
        out.append(f"  date: {yaml_str(date)}")
        out.append(f"  is_repost: {'true' if is_repost else 'false'}")
        out.append(f"  body: {yaml_str(body)}")
        if images:
            out.append("  images:")
            for src in images:
                out.append(f"    - {src}")
        else:
            out.append("  images: []")
        fetched += 1

    DST.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"\nDone. {fetched} fetched, {skipped} skipped. Wrote {DST}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
